### ISSUE TITLE
Deployment to Bluemix fails with  Cannot find module '/home/vcap/app/app.js

### ISSUE THREAD

**Issue by ptitzler** [IBM-Bluemix/cf-deployment-tracker-service#158]
Starting app instance (index 0) with guid 3258a8cf-68eb-4645-b1b4-b04c85b4d25a
    module.js:327
    throw err;
    ^
Error: Cannot find module '/home/vcap/app/app.js
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by ptitzler** [comment]
The problem seems to be somehow caused by the `Procfile`, which contains the following entry `web: node app.js`. File `app/app.js` is present, not sure why node cannot load it. The application starts fine if that file is renamed/removed.

**Comment by aryanfaghihi** [comment]
@ptitzler Thanks for reporting this. I spent hours trying to figure out what was wrong and this saved the day. Deleting `Procfile` definitely solves the problem.
