### ISSUE TITLE
Deployment post install step fails

### ISSUE THREAD

**Issue by ptitzler** [IBM-Bluemix/cf-deployment-tracker-service#183]
From `package.json`: `"postinstall": "bower install --config.interactive=false --allow-root && ./admin.js track && ./admin.js db put && ./admin.js ddoc put && ./admin.js clean repository_url_hash",`

Console output:
```
-----> Building dependencies

       Pruning any extraneous modules

       Installing node modules (package.json)

       > deployment-tracker@0.1.0 postinstall /tmp/staged/app

       > bower install --config.interactive=false --allow-root && ./admin.js track && ./admin.js db put && ./admin.js ddoc put && ./admin.js clean repository_url_hash

       bower respond#*             not-cached https://github.com/scottjehl/Respond.git#*

       bower respond#*                resolve https://github.com/scottjehl/Respond.git#*

       bower jquery#*              not-cached https://github.com/jquery/jquery-dist.git#*

       bower jquery#*                 resolve https://github.com/jquery/jquery-dist.git#*

       bower html5shiv#*           not-cached https://github.com/aFarkas/html5shiv.git#*

       bower html5shiv#*              resolve https://github.com/aFarkas/html5shiv.git#*

       bower zeroclipboard#*       not-cached https://github.com/zeroclipboard/zeroclipboard.git#*

       bower zeroclipboard#*          resolve https://github.com/zeroclipboard/zeroclipboard.git#*

       bower bootstrap#*           not-cached https://github.com/twbs/bootstrap.git#*

       bower bootstrap#*              resolve https://github.com/twbs/bootstrap.git#*

       bower respond#*               checkout 1.4.2

       bower html5shiv#*             checkout 3.7.3

       bower jquery#*                checkout 3.1.0

       bower respond#*               resolved https://github.com/scottjehl/Respond.git#1.4.2

       bower html5shiv#*             resolved https://github.com/aFarkas/html5shiv.git#3.7.3

       bower zeroclipboard#*         resolved https://github.com/zeroclipboard/zeroclipboard.git#2.2.0

       bower jquery#*                resolved https://github.com/jquery/jquery-dist.git#3.1.0

       bower bootstrap#*             resolved https://github.com/twbs/bootstrap.git#3.3.7

       bower respond#*                install respond#1.4.2

       bower html5shiv#*              install html5shiv#3.7.3

       bower zeroclipboard#*          install zeroclipboard#2.2.0

       bower jquery#1.9.1 - 3         install jquery#3.1.0

       bower bootstrap#*              install bootstrap#3.3.7

       respond#1.4.2 public/assets/respond

       html5shiv#3.7.3 public/assets/html5shiv

       zeroclipboard#2.2.0 public/assets/zeroclipboard

       jquery#3.1.0 public/assets/jquery

       bootstrap#3.3.7 public/assets/bootstrap

       └── jquery#3.1.0

       { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }

       Uploaded stats { ok: true }

       { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }

       Deployment tracker events database already exists

       { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }

       Design document updated

       { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }

       /tmp/staged/app/admin.js:197

       console.log(body.rows.length + " documents without repository URL hashes");

       ^

       TypeError: Cannot read property 'rows' of undefined

       at /tmp/staged/app/admin.js:197:27

       at Request._callback (/tmp/staged/app/node_modules/cloudant/node_modules/nano/lib/nano.js:241:7)

       at Request.self.callback (/tmp/staged/app/node_modules/cloudant/node_modules/nano/node_modules/request/request.js:187:22)

       at emitTwo (events.js:87:13)

       at Request.emit (events.js:172:7)

       at Request.<anonymous> (/tmp/staged/app/node_modules/cloudant/node_modules/nano/node_modules/request/request.js:1044:10)

       at emitOne (events.js:77:13)

       at Request.emit (events.js:169:7)

       at IncomingMessage.<anonymous> (/tmp/staged/app/node_modules/cloudant/node_modules/nano/node_modules/request/request.js:965:12)

       at emitNone (events.js:72:20)

       npm ERR! Linux 3.19.0-33-generic

       npm ERR! argv "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/staged/app/.npmrc"

       npm ERR! node v4.4.7

       npm ERR! npm  v2.15.8

       npm ERR! code ELIFECYCLE

       npm ERR! deployment-tracker@0.1.0 postinstall: `bower install --config.interactive=false --allow-root && ./admin.js track && ./admin.js db put && ./admin.js ddoc put && ./admin.js clean repository_url_hash`

       npm ERR! Exit status 1

       npm ERR!

       npm ERR! Failed at the deployment-tracker@0.1.0 postinstall script 'bower install --config.interactive=false --allow-root && ./admin.js track && ./admin.js db put && ./admin.js ddoc put && ./admin.js clean repository_url_hash'.

       npm ERR! This is most likely a problem with the deployment-tracker package,

       npm ERR! not with npm itself.

       npm ERR! Tell the author that this fails on your system:

       npm ERR!     bower install --config.interactive=false --allow-root && ./admin.js track && ./admin.js db put && ./admin.js ddoc put && ./admin.js clean repository_url_hash

       npm ERR! You can get information on how to open an issue for this project with:

       npm ERR!     npm bugs deployment-tracker

       npm ERR! Or if that isn't available, you can get their info via:

       npm ERR!

       npm ERR!     npm owner ls deployment-tracker

       npm ERR! There is likely additional logging output above.

       npm ERR! Please include the following file with any support request:

       npm ERR!     /tmp/staged/app/npm-debug.log

-----> Build failed

       Some possible problems:

       - Node version not specified in package.json

       http://docs.cloudfoundry.org/buildpacks/node/node-tips.html

Staging failed: Buildpack compilation step failed
```

**Comment by ptitzler** [comment]
Delivered by #184
